### ISSUE TITLE
有点意思

### ISSUE THREAD

**Issue by pocketvision** [MRzzm/AdaAT#3]
个人觉得AdaAT算是FOMM类方法中出现的比较有意思的尝试，但我有个疑问想请教一下，我看作者构建的模型中，Appearance Encoder的输入中直接带有驱动目标的关键点信息，一般来说这样编解码，即使没有AdaAT的对Appearance Feature的deformation，应该也是能生成出对应的驱动结果的，这样就比较难说明实际生成结果主要是由AdaAT对Appearance Feature作用后生成的结果，还是利用Appearance Encoder中的驱动目标信息来生成的结果，不知道这样理解对不对？

**Comment by daikankan** [comment]
请教一下，我尝试将驱动信息分离出来，只有预测trans_para的网络是包含驱动关键点信息的情况下，训练结果显示：能学习到人头的旋转缩放平移，但表情学习不到，使用2D关键点，似乎也验证了上面的猜测（左：原始人脸，中：驱动人脸，右生成结果）：
![src_drv_fake_512x512](https://github.com/MRzzm/AdaAT/assets/20749514/efe64108-5761-4dce-bb5b-b008d156edf1)
![src_drv_fake_512x512 _2](https://github.com/MRzzm/AdaAT/assets/20749514/82687ba5-9efa-471e-a084-86c7595c3c1d)
![src_drv_fake_512x512_1](https://github.com/MRzzm/AdaAT/assets/20749514/7b2c67d5-b44e-4fd9-8e50-1104beef1720)

**Comment by daikankan** [comment]
而我基于FOMM类方法能做到如下结果：
（左：原始人脸，中：驱动人脸，右：生成结果）
![src_drv_fake_512x512 (4)](https://github.com/MRzzm/AdaAT/assets/20749514/78bfa7da-bbd8-4633-a873-9bfb19d5d73e)
![src_drv_fake_512x512 (3)](https://github.com/MRzzm/AdaAT/assets/20749514/b4fc06e4-3cce-44ee-9d0b-ae24ab384a86)
![src_drv_fake_512x512](https://github.com/MRzzm/AdaAT/assets/20749514/f7dcf5eb-3fe6-4e6e-98b7-7c0f46d8fae7)
